name: denni_evidence
description: A simple Flutter app for daily task tracking
publish_to: "none" # Tento projekt nebude publikován na pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # Přidej další závislosti, pokud je používáš
  shared_preferences: ^2.2.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Zde můžeš přidat své obrázky nebo jiné assety
    # - assets/images/
